inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rails-accessibility

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-erb
  - rubocop-packaging

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: true
  AllowedChars: ['à', 'é', 'è', 'ë', 'ê', 'î', 'ï', 'ô', 'ù', 'ç', 'À', 'É', 'È', 'Ë', 'Ê', 'Î', 'Ï', 'Ô', 'Ù', 'Ç']

Layout/LineLength:
  Enabled: true
  Max: 100

Style/SymbolProc:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/factories/*'
    - 'Guardfile'
    - 'app/**/*.arb'
  AllowedMethods:
    - describe
    - it
    - resource
    - register
    - register_page
    - route_param
    - context
    - show
    - controller
    - namespace
    - xls

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'spec/models/restitution/inventaire/rapidite_spec.rb'
    - 'spec/models/restitution/controle/perseverance_spec.rb'
    - 'spec/models/restitution/inventaire/perseverance_spec.rb'
    - 'spec/models/restitution/tri/perseverance_spec.rb'
    - 'spec/models/restitution/tri/comprehension_consigne_spec.rb'

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - 'app/components/**/*'

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - 'spec/tasks/**/*'
