class UpdateCategorieQuestion < ActiveRecord::Migration[7.0]
  def up
    Question.find_by(nom_technique: 'age')
      &.update(libelle: 'Âge', categorie: :situation)
    Question.find_by(nom_technique: 'genre')
      &.update(categorie: :situation, libelle: 'Genre')
    Question.find_by(nom_technique: 'langue_maternelle')
      &.update(categorie: :situation, libelle: 'Français langue maternelle')
    Question.find_by(nom_technique: 'derniere_situation')
      &.update(categorie: :situation, libelle: 'Dernière situation')
    Question.find_by(nom_technique: 'lieu_scolarite')
      &.update(categorie: :scolarite, libelle: "Lieu de scolarité")
    Question.find_by(nom_technique: 'dernier_niveau_etude')
      &.update(categorie: :scolarite, libelle: "niveau d'étude")
    Question.find_by(nom_technique: 'bienvenue_12')
      &.update(categorie: :appareils, libelle: 'écrans')
    Question.find_by(nom_technique: 'bienvenue_13')
      &.update(categorie: :appareils, libelle: 'ordinateur')
    Question.find_by(nom_technique: 'bienvenue_14')
      &.update(categorie: :appareils, libelle: 'tablette')
    Question.find_by(nom_technique: 'difficultes_informatique')
      &.update(categorie: :appareils, libelle: "Difficultés avec l'informatique")
    Question.find_by(nom_technique: 'vue')&.update(categorie: :sante, libelle: 'Vue')
    Question.find_by(nom_technique: 'bienvenue_9')&.update(categorie: :sante, libelle: 'Couleur')
    Question.find_by(nom_technique: 'entendre')&.update(categorie: :sante, libelle: 'Audition')
    Question.find_by(nom_technique: 'bienvenue_11')&.update(categorie: :sante, libelle: 'Concentration')
    Question.find_by(nom_technique: 'trouble_dys')&.update(categorie: :sante, libelle: 'Troubles dys')
  end
end
